version: '2'
services:
  website:
    container_name: php72
    build:
      context: ./
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql
  mysql:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}
          - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
        restart: 'always'
        ports:
          - 13306:3306